version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - appnet

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "4000"
    healthcheck:
      # Make sure your API exposes GET /health returning 200 OK
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      # If you already have TLS, map 443 too and supply a TLS-enabled conf
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api:
        condition: service_healthy
    networks:
      - appnet

volumes:
  redis-data:

networks:
  appnet:
    driver: bridge
